# Generated by Django 5.1.4 on 2024-12-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passuser',
            name='firstname',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='passuser',
            name='lastname',
            field=models.CharField(blank=True, max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='passuser',
            name='surname',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отчество'),
        ),
    ]
