# Generated by Django 5.1.4 on 2024-12-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passuser_firstname_passuser_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passuser',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('moderated', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
